# Generated by Django 5.2.11 on 2026-04-16 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0003_shift_employee_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('lock', 'Lock Workstation'), ('screenshot', 'Capture Screenshot'), ('terminate', 'Terminate Process')], max_length=50)),
                ('parameters', models.JSONField(blank=True, help_text="e.g. {'pid': 1234}", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='tracker_api.device')),
            ],
        ),
        migrations.CreateModel(
            name='AgentScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='tracker_api.device')),
                ('trigger_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker_api.securityevent')),
            ],
        ),
    ]
