# Generated by Django 5.2.11 on 2026-04-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0004_agentcommand_agentscreenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('install_date', models.CharField(blank=True, max_length=100, null=True)),
                ('is_authorized', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_apps', to='tracker_api.device')),
            ],
            options={
                'unique_together': {('device', 'app_name')},
            },
        ),
    ]
