# Generated by Django 5.2.11 on 2026-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0005_installedapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='Exact name of the application to flag as unauthorized', max_length=255, unique=True)),
                ('risk_weight', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
