# Generated by Django 5.2.11 on 2026-04-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0006_blacklistedapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentscreenshot',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentscreenshot',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
