# Generated by Django 5.2.11 on 2026-04-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0007_agentscreenshot_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapp',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
