# Generated by Django 5.2.11 on 2026-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0008_installedapp_last_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsession',
            name='is_installed_app',
            field=models.BooleanField(default=False, help_text='True if this matches an entry in InstalledApp'),
        ),
    ]
