# Generated by Django 5.2.11 on 2026-04-30 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0009_appsession_is_installed_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('check-in', 'Check-In'), ('check-out', 'Check-Out'), ('break-start', 'Break Start'), ('break-end', 'Break End')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='tracker_api.device')),
            ],
        ),
    ]
